### ISSUE TITLE
Is it really necessary for NilLoader to include a decompiler?

### ISSUE THREAD

**Issue by Ecdcaeb** [unascribed/NilLoader#3]
Is it really necessary for NilLoader to include a decompiler?
Currently, vineflower, a replacement for quiltflower, requires Java 11, which is not suitable for this project. However, higher versions of Java classes are not supported without updates. In addition, the built-in decompiler is not easy to use. Maybe we can move this content out of NilLoader and build a separate decompiler, or recommend other decompilers. We don't need to include decompilation in NilLoader.

**Comment by unascribed** [comment]
Vineflower is an optional runtime dependency for convenience when doing debugging and diffing. It's provided because *I use it*, as manually decompiling .class files is tedious, and that is sufficient justification for its inclusion.
